services:
  api:
    build:
      context: .
      dockerfile: packages/api-server/Dockerfile
    ports:
      - 127.0.0.1:8001:3000
    volumes:
      - uploads_volume:/app/uploads
    depends_on:
      - database
    environment:
      NODE_ENV: production
      BOKARI_UPLOADS_STORAGE_DIR: /app/uploads
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: database
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: changeme2
      TYPEORM_DATABASE: bokari
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "false"
      JWT_PRIVATE_KEY:
      JWT_PUBLIC_KEY:
  ui:
    build:
      context: .
      args:
        VUE_APP_BOKARI_API_URL: "http://127.0.0.1:8001"
      dockerfile: packages/ui/Dockerfile
    ports:
      - 127.0.0.1:8002:80
  uploads:
    build:
      context: .
      dockerfile: packages/uploads/Dockerfile
    ports:
      - 127.0.0.1:8003:80
    volumes:
      - uploads_volume:/usr/share/nginx/html
  database:
    image: postgres
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bokari
      POSTGRES_PASSWORD: changeme2
volumes:
  uploads_volume:
  database_volume:
